import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>List of Books and Authors</title>
        <meta name="description" content="Generated by Sol Garcia"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <a href={'/bookForm'}>+ Add Book</a>
      </main>
      <style jsx>{`
        .container {
          padding: 0 2rem;
        }

        main {
          min-height: 100vh;
          padding: 4rem 0;
          flex: 1;
          display: flex;
          flex-direction: column;
          justify-content: center;
          align-items: center;
        }
        
        h1 a {
          color: #0070f3;
          text-decoration: none;
        }

        h1 a:hover,
        h1 a:focus,
        h1 a:active {
          text-decoration: underline;
        }

        h1 {
          margin: 0;
          line-height: 1.15;
          font-size: 4rem;
          text-align: center;
        }
      `}</style>
      <style jsx global>{`
        html,
        body {
          padding: 0;
          margin: 0;
          font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen,
          Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif;
        }

        a {
          color: inherit;
          text-decoration: none;
        }

        * {
          box-sizing: border-box;
        }

        @media (prefers-color-scheme: dark) {
          html {
            color-scheme: dark;
          }

          body {
            color: white;
            background: black;
          }
        }

      `}</style>
    </div>
  )
}

export default Home
