import type {NextPage} from 'next'
import {useEffect, useState} from "react"
import Head from 'next/head'
import Link from "next/link"
import BookCard from "../components/BookCard";

export interface BookType {
  id: number
  name: string
  authorName: string
  description: string
}

const Home: NextPage = () => {
  const [books, setBooks] = useState<BookType[]>([])

  useEffect(() => {
    const getBooks = async () => {
      const res = await fetch('http://localhost:3010/books')
      setBooks(await res.json())
    }
    getBooks()
  }, [])
  return (
    <div className="container">
      <Head>
        <title>List of Books and Authors</title>
        <meta name="description" content="Generated by Sol Garcia"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://github.com/solgarcia2002/books">BOOK me</a>
        </h1>
        <Link href={'/bookForm'}><a className={'addBook'}>+ Add Book</a></Link>
        <div className={'bookContainer'}>
          {books.length && books.map((book) => (
            <BookCard bookData={book} key={book.id}/>
          ))
          }
        </div>
      </main>
      <style jsx>{`
        .container {
          padding: 0 2rem;
        }

        main {
          min-height: 100vh;
          padding: 4rem 0;
          flex: 1;
          display: flex;
          flex-direction: column;
          justify-content: center;
          align-items: center;
        }

        a {
          color: #0070f3;
          text-decoration: none;
        }

        h1 a:hover,
        h1 a:focus,
        h1 a:active {
          text-decoration: underline;
        }

        h1 {
          margin: 0;
          line-height: 1.15;
          font-size: 4rem;
          text-align: center;
        }

        .bookContainer {
          display: flex;
          flex-direction: row;
          gap: 2rem;
          flex-wrap: wrap;
          max-width: 100%;
          justify-content: center;
        }

        .addBook {
          align-self: flex-end;
          margin: 2rem 20%;
        }
      `}</style>
      <style jsx global>{`
        html,
        body {
          padding: 0;
          margin: 0;
          font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen,
          Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif;
        }

        a {
          color: inherit;
          text-decoration: none;
        }

        * {
          box-sizing: border-box;
        }

        @media (prefers-color-scheme: dark) {
          html {
            color-scheme: dark;
          }

          body {
            color: white;
            background: black;
          }
        }

      `}</style>
    </div>
  )
}

export default Home
