import Link from "next/link";
import Head from "next/head";
import React, {useEffect, useState} from "react";
import {Button, TextField, Box,Alert, Stack} from "@mui/material";
import CheckIcon from '@mui/icons-material/Check';

interface AuthorType {
  id: number
  name: string
}

const BookForm = () => {
  const [authors, setAuthors] = useState<AuthorType[]>([])
  const [currentAuthor, setCurrentAuthor] = useState<number>(0)
  const [currentBookName, setCurrentBookName] = useState<string>('')
  const [currentBookDescription, setCurrentBookDescription] = useState<string>('')
  const [submitMessage, setSubmitMessage] = useState<string>('')
  useEffect(() => {
    const getBooks = async () => {
      const res = await fetch('http://localhost:3010/authors')
      setAuthors(await res.json())
    }
    getBooks()
  }, [])
  useEffect(() => {
    if (!authors.length) return
    setCurrentAuthor(authors[0].id)
  }, [authors])

  const handleChangeAuthor = (event: React.ChangeEvent<HTMLInputElement>) => {
    const selectedAuthor = event.target.value ?? 0;
    setCurrentAuthor(Number.parseInt(selectedAuthor))
  }
  const handleAddBook = () => {
    const requestOptions = {
      method: 'POST',
      headers: {'Content-Type': 'application/json'},
      body: JSON.stringify({
        name: currentBookName,
        description: currentBookDescription,
        authorId: currentAuthor})
    };
    setCurrentBookDescription('')
    setCurrentAuthor(authors[0].id)
    setCurrentBookName('')
    fetch('http://localhost:3010/books', requestOptions)
      .then(response => {
        setSubmitMessage('Your book has been added')
        setTimeout(()=>{setSubmitMessage('')},3000)
      })
  }
  return <>
    <div className="container">
      <Head>
        <title>List of Books and Authors - Add Book</title>
        <meta name="description" content="Generated by Sol Garcia"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main>
        <h1>
          Welcome to <a href="https://github.com/solgarcia2002/books">BOOK me</a>
        </h1>
        <Link href={'/'}><a> Go Back Home</a></Link>
        <Box
          component="form"
          sx={{
            '& .MuiTextField-root': {m: 1, width: '25ch'},
          }}
        >
          <div className={'formContent'}>
            <TextField
              className={'formItem'}
              id="bookName"
              label="Book Name"
              defaultValue={currentBookName}
              variant="standard"
              value={currentBookName}
              helperText="Please select the book's name"
              onChange={(e) => {
                setCurrentBookName(e.target.value)
              }}
            />
            <TextField
              className={'formItem'}
              multiline
              rows={4}
              id="bookDescription"
              label="Book Description"
              defaultValue={currentBookDescription}
              value={currentBookDescription}
              variant="standard"
              helperText="Please select the book's description"
              onChange={(e) => {
                setCurrentBookDescription(e.target.value)
              }}
            />
            <TextField
              className={'formItem'}
              select
              id="bookAuthor"
              label="Book's Author"
              value={currentAuthor}
              SelectProps={{
                native: true,
              }}
              onChange={handleChangeAuthor}
              helperText="Please select the book's author"
              variant="standard"
            >
              {authors.map((option: AuthorType) => (
                <option key={option.id} value={option.id}>
                  {option.name}
                </option>
              ))}
            </TextField>
            <Stack sx={{ width: '100%' }} spacing={2}>
              {submitMessage && <Alert icon={<CheckIcon fontSize="inherit" />} severity="success">
                {submitMessage}
              </Alert>}
            </Stack>
            <Button variant="contained" onClick={handleAddBook}>Submit Book</Button>
          </div>
        </Box>

      </main>
    </div>
    <style jsx>{`
      .container {
        padding: 0 2rem;
      }

      main {
        margin: 0;
        min-height: 100vh;
        padding: 4rem 0;
        flex: 1;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
      }

      h1 a {
        color: #0070f3;
        text-decoration: none;
      }

      h1 a:hover,
      h1 a:focus,
      h1 a:active {
        text-decoration: underline;
      }

      h1 {
        margin: 0;
        line-height: 1.15;
        font-size: 4rem;
        text-align: center;
        font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen,
        Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif;

      }

      .formContent {
        display: flex;
        flex-direction: column;
        width: 30rem;
      }

      .formItem {
        width: 30rem;
      }
    `}</style>
  </>
}
export default BookForm
